import re
with open('main.tex', 'r') as f:
    text = f.read()

# Fix the literal \n error
text = text.replace(r'\clearpage\n\pagenumbering{arabic}\n\setcounter{page}{1}\n', 
                    '\\clearpage\n\\pagenumbering{arabic}\n\\setcounter{page}{1}\n')

# Also fix the \\\\\\\\ generated by my previous script
text = re.sub(r'\\\\\\\\(\w)', r'\\\\ \1', text)

with open('main.tex', 'w') as f:
    f.write(text)
